import type {Metadata} from "next";
import {Inter, Montserrat} from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/index";
import FooterPage from "./footer/index";
import TransitionEffect from './components/transitionEffect'
const montserrat = Montserrat({subsets: ["latin"], variable: '--font-mont'});

export const metadata: Metadata = {
    title: "Lưu Gia Xuân Bảo-Frontend Dev",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
        <body className={`${montserrat.className} dark:bg-dark h-screen`}>
        <TransitionEffect>
            <Navbar/>
            {children}
            <FooterPage/>
        </TransitionEffect>
        </body>
        </html>
    );
}
